version: "3.7"

services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
      MYSQL_HOSTNAME: 'mysql'
    volumes:
      - my-datavolume:/var/lib/mysql
  www:
    depends_on:
      - db
    links:
      - "db:mysql"
    image: php:7.4.18-apache
    volumes:
      - "./doc_root/:/var/www/html"
    build:
      "context": "./"
      "dockerfile": "Dockerfile-apache"
    ports:
      - 80:80
      - 443:443
    environment:
      PHP__display_errors: 'On'
      PHP_php5enmod: 'php_mysql'
      PHP__date.timezone: '"America/Los_Angeles"'
      PHP__short_open_tag: 'On'
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
volumes:
  my-datavolume:
